// This file will be generated by Supabase CLI
// For now, we use a placeholder type
export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            products: {
                Row: {
                    id: string
                    name: string
                    description: string
                    price: number
                    category: string
                    stock: number
                    images: string[]
                    specifications: Json
                    whatsapp_number: string
                    whatsapp_message: string | null
                    active: boolean
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    description: string
                    price: number
                    category: string
                    stock?: number
                    images?: string[]
                    specifications?: Json
                    whatsapp_number: string
                    whatsapp_message?: string | null
                    active?: boolean
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    description?: string
                    price?: number
                    category?: string
                    stock?: number
                    images?: string[]
                    specifications?: Json
                    whatsapp_number?: string
                    whatsapp_message?: string | null
                    active?: boolean
                    created_at?: string
                    updated_at?: string
                }
            }
        }
    }
}
