// This file will be generated by Supabase CLI
// For now, we use a placeholder type
export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export type PricingMode = 'quote' | 'starting_price'

export interface Database {
    public: {
        Tables: {
            products: {
                Row: {
                    id: string
                    name: string
                    description: string
                    price: number
                    pricing_mode: PricingMode
                    category: string
                    stock: number
                    images: string[]
                    specifications: Json
                    whatsapp_number: string
                    whatsapp_message: string | null
                    active: boolean
                    is_promotion: boolean
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    description: string
                    price: number
                    pricing_mode?: PricingMode
                    category: string
                    stock?: number
                    images?: string[]
                    specifications?: Json
                    whatsapp_number: string
                    whatsapp_message?: string | null
                    active?: boolean
                    is_promotion?: boolean
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    description?: string
                    price?: number
                    pricing_mode?: PricingMode
                    category?: string
                    stock?: number
                    images?: string[]
                    specifications?: Json
                    whatsapp_number?: string
                    whatsapp_message?: string | null
                    active?: boolean
                    is_promotion?: boolean
                    created_at?: string
                    updated_at?: string
                }
            }
            product_analytics: {
                Row: {
                    id: string
                    product_id: string
                    event_type: string
                    created_at: string
                }
                Insert: {
                    id?: string
                    product_id: string
                    event_type?: string
                    created_at?: string
                }
                Update: {
                    id?: string
                    product_id?: string
                    event_type?: string
                    created_at?: string
                }
            }
        }
        Views: {
            product_analytics_summary: {
                Row: {
                    id: string | null
                    name: string | null
                    category: string | null
                    total_clicks: number | null
                    clicks_today: number | null
                    clicks_week: number | null
                    clicks_month: number | null
                    last_click_at: string | null
                }
            }
        }
        Functions: {}
    }
}
